version: '3.8'

services:
  arrow-scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: arrow-scraper
    restart: unless-stopped

    ports:
      - "5060:5000"

    volumes:
      - /volume1/docker/arrow_scraper/data/exports:/app/exports
      - /volume1/docker/arrow_scraper/data/logs:/app/logs
      - /volume1/docker/arrow_scraper/data:/app/data
      - /volume1/docker/arrow_scraper/.env:/app/.env:ro

    env_file:
      - /volume1/docker/arrow_scraper/.env

    environment:
      - DATABASE_PATH=/app/data/arrow_scraper.db
      - LOG_FILE=/app/logs/arrow_scraper.log
      - LOG_LEVEL=INFO
      - TZ=Europe/Berlin
      - WEB_HOST=0.0.0.0
      - WEB_PORT=5000
      - FLASK_ENV=production
      - DEBUG=false
      - ARROW_BASE_URL=https://www.arrow.it
      - ARROW_API_BASE=https://www.arrow.it/api/en
      - REQUEST_TIMEOUT=30
      - REQUEST_DELAY=0.3
      - SECRET_KEY=arrow_scraper_secret_key_2024

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    labels:
      - "com.docker.compose.project=arrow-scraper"
      - "com.docker.compose.service=arrow-scraper"
      - "description=Arrow.it Scraper - Produktdaten-Extraktor für Arrow.it"
      - "traefik.enable=true"
      - "traefik.http.routers.arrow-scraper.rule=Host(`arrow-scraper.local`)"
      - "traefik.http.routers.arrow-scraper.entrypoints=web"
      - "traefik.http.services.arrow-scraper.loadbalancer.server.port=5000"
